# Generated by Django 5.1.4 on 2024-12-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matibi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='nookhubarticles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
